### PR TITLE
Update production with changes on staging

### LINKED ISSUE #32: Site loads very slow on some browsers / connections
Some users are reporting very slow load times for the website; it sits for a long time fetching/loading the Polymer assets, most notably on Firefox.

We need to run some profiling of the site to see where the delays are coming from and improve the responsive loading.

### LINKED ISSUE #45: "Get Help" is not sending email
Help requests are being logged to a file and manually pulled down. The system should be sending an email to support at minnowboard.org with each web submission.

### PR DESCRIPTION
**Pull request by jketreno**
Fixes in staging:

* Fix #32 - Add vulcanized build to website
* Fix #45 - Add mail to support@ instead of only writing to message file when web support requests are submitted

### CODE REVIEW

**Comment by ebrent8** [comment]
None of the tutorials are not loading for me on stg
https://stg.minnowboard.org/tutorials/powering-on-minnowboardturbot

**Comment by jketreno** [comment]
@ebrent8 Indeed; it appears direct linking to the tutorials is breaking. Thanks!

**Comment by valigatorCA** [comment]
https://stg.minnowboard.org/tutorials/ftdi-serial-connection - photos not loading

**Comment by jketreno** [comment]
@ebrent8 @valigatorCA I believe I have it fixed now in the merge request; can you test around on https://stg.minnowboard.org again and see if you find any more problems?

Thanks,
James

**Comment by ebrent8** [comment]
It all loads and works fine for me.

**Pull request merged**
